### ISSUE TITLE
Add HTTP proxy support

### ISSUE THREAD

**Issue by mooleshacat** [YunzheZJU/youtube-po-token-generator#1]
Hi

I have forked your repo ( https://github.com/mooleshacat/youtube-po-token-generator ) and added unauthenticated HTTP proxy support but I am not good at programming and changed the http.get over to a request. I used request because it was the only way I could find to get the proxy to work.

I was wondering if you could add proxy support to the code.

I would much rather use your code instead but it does not support proxy.

Thanks :)

**Comment by YunzheZJU** [comment]
Thank you for your suggestion.

It is said that Node.js would find and use the proxy settings from env, which is to say, this should work for static https proxy configurations:

```bash
export HTTP_PROXY=http://proxy-server.com:8080
export HTTPS_PROXY=http://proxy-server.com:8080
node index.js
```

Commands change on Windows but that is not difficult to find out.

There also exists a lib named [global-agent](https://www.npmjs.com/package/global-agent) to simply add proxy for all requests in Node.js, which can also be transparent to `youtube-po-token-generator`.

```node
require('global-agent/bootstrap')

global.GLOBAL_AGENT.HTTP_PROXY = 'http://proxy-server.com:8001'

const { generate } = require('youtube-po-token-generator')

generate(options).then(console.log, console.error)
```

I can help you if you have tried the methods above but nothing works.

**Comment by mooleshacat** [comment]
Ok, I will try the first one. If I still can't get it to work I will re-open ticket.

I just find it hard to tell if it is actually working over the proxy or not but I am sure I can test it somehow.

Thank you :)

**Comment by mooleshacat** [comment]
I put `export HTTP_PROXY=192.168.10.201:8888` and when I run a test script that goes to get the current IP it still shows it as my naked IP and not my VPN IP. I don't think this environment variable has any effect at all on the nodeJS code.

I will keep poking around with it but I'll keep the ticket open for now.

**Comment by mooleshacat** [comment]
I think I give up and don't want to waste your time so closing ticket

**Comment by mooleshacat** [comment]
Reopened to say I figured the easy way out, you have to specify both HTTP_PROXY and HTTPS_PROXY as the same http:// proxy.

When I curl ipinfo.io/ip now I get VPN IP. Thanks 👍
