### ISSUE TITLE
one-shot generates the same po_token every time?

### ISSUE THREAD

**Issue by cleong110** [YunzheZJU/youtube-po-token-generator#2]
Reproducing: https://colab.research.google.com/drive/190BC9tEc0wTtCsfSbWHY-lT6amjSwFyG#scrollTo=M8mz73yeureD

Every time I run it, I get exactly the same result:

```
{
  visitorData: 'CgszZTdjbENPLTVXZyjz46y3BjIKCgJVUxIEGgAgWA%3D%3D',
  poToken: 'MnS5xDIuZoiXYLn8SsESl2DKEHCDthoVv2NovkQqiuvqFDyUUM_qGlkHJvMNRy28LvvMrSCgv9Y25evjBF1ECzVYBDjnbvzoreBA0GaNya4_JqW2WXLnsDDo4XHTn_wLJB6eBXjA15OU2seDwTDGPYAuA7BFJQ=='
}
```

Shouldn't it get a new one somehow?

**Comment by YunzheZJU** [comment]
Gonna verify this case next week. 
Have you reproduced it on your own machine?
The special runtime provided by colab may affect the result.

**Comment by cleong110** [comment]
Managed to get it running in Powershell on Windows: It does not happen there, giving different results each time. Good call!

node --version
v20.14.0

**Comment by cleong110** [comment]
And now that I rerun it in colab, it seems to have stopped happening. Not sure what changed. Sorry!
