### ISSUE TITLE
how to use proxy

### ISSUE THREAD

**Issue by farjar** [YunzheZJU/youtube-po-token-generator#7]
how to use proxy

**Comment by YunzheZJU** [comment]
Please refer to #1.

**Comment by farjar** [comment]
solved. thks very much. this is my example code:
`require('global-agent/bootstrap')

global.GLOBAL_AGENT.HTTP_PROXY = 'http://192.168.2.2:7890'

const { generate } = require('youtube-po-token-generator')

generate().then(console.log, console.error)`
