### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by bzqadmin** [YunzheZJU/youtube-po-token-generator#8]
Can anybody tell me why?

`$ npm start

> y@1.0.0 start
> node index.js

Error: connect ETIMEDOUT 31.13.112.9:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '31.13.112.9',
  port: 443
}`

**Comment by YunzheZJU** [comment]
Please try `curl https://www.youtube.com` directly in your terminal to confirm your connectivity to youtube.

Also refer to #1 to make sure node is using your system proxy conf if there is any.
